title: Aiding RL training with LLM and VLMs
description: Group members: Sahire Ellahy, Jim An

remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
